# Parasprite Radio config file

[general]
media_dir = "/nas/audio"
baseurl   = "http://radiodev.djazz.se/"
streamurl = "http://icecast.djazz.se:5000/radio"
userAgent = "ParaspriteRadio/0.0.0"

# info about radio - used on the site and for Icecast metadata
[radio]
title       = "Parasprite Radio"
description = ""
genre       = "Misc"
url         = "http://radio.djazz.se"


# streaming server
[icecast]
host     = "localhost"
port     = 8000

# what mounts too look for listeners on
mounts   = [ "radio", "radio_mobile" ]
encoding = "UTF-8"

[icecast.mount]
user     = "source"
password = "hackme"

[icecast.admin]
user     = "admin"
password = "hackme"

[[icecast.relay]]
host = "icecast.djazz.se"
port = 5000
password = "hackme"



# the thing where magic happens
[liquidsoap]
host = "localhost"
port_telnet = 1234
port_harbor = 7000
port_input  = 8001


# music database
[mpd]
host     = "localhost"
port     = 6600
password = ""

# the nodejs server
[server]
host = "localhost"
port = 8002
cookieSecret  = "secret"
sessionSecret = "secret"

# database
[mysql]
host     = "localhost"
user     = "root"
password = ""
database = "paraspriteradio"

# session storage
[redis]
host = "localhost"
port = 6379
prefix = "pr-sess"

# for Twitter authentication
[twitter]
consumerKey = ""
consumerSecret = ""
callbackURL = "http://radiodev.djazz.se/auth/twitter/callback"

# for scheduling
[google]
apiKey = "AIzaSyDoDqSmr8f3MaO5RTzPZ8NZexAJF8MlK5A"
calendarId = "nj4dn0ck0u66t6f38qtqnj324k@group.calendar.google.com"


# scrobbling
[lastfm]
username = "djazzradio"
password = ""

[tunein]
stationId  = "s225092"
partnerId  = ""
partnerKey = ""


# external sources
[soundcloud]
clientId = ""

[spotify]
username = "ParaspriteRadio"
password = ""
